[profile.dev]
debug = 0
incremental = false

[profile.test]
debug = 0
incremental = false

[profile.release]
debug = 0
incremental = false
strip = "symbols"

[profile.bench]
debug = 0
incremental = false
strip = "symbols"
