[package]
name = "miniflow-flowlog-batch-corpus"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
default-run = "miniflow-flowlog-batch-corpus"

[dependencies]
miniflow.workspace = true
miniflow-core.workspace = true
ordered-float.workspace = true
proc-macro2.workspace = true
quote.workspace = true

[lints]
workspace = true
